# Run This command in order for the ELK container to work.
# sudo sysctl -w vm.max_map_count=262144
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - .:/config-dir
    command: logstash -f /config-dir/logstash-simple.conf
  apm:
    image: docker.elastic.co/apm/apm-server:7.2.0
    container_name: apm
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esdata1:
    driver: local